### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Theo-Reeves** [dogerish/tictactoe#1]
- [ ] Make a Replay button
- [ ] Update Visuals
- [ ] Turn the winners green
- [ ] Randomly select first turn
